### ISSUE TITLE
Support for customer-defined CNAMES

### ISSUE THREAD

**Issue by pchico83** [okteto/cloud-feedback#13]
When sharing a dev environment, some customers prefer their own domain (e.g. sample.example.com) instead of the okteto url.
 Certificates should be auto generated

**Comment by toonsevrin** [comment]
Being able to point a CNAME to the generated endpoint would be nice for our developer UX as well. 

The main benefit for them being that the url is a lot shorter and easier to remember.

This should not be considered high priority in my opinion, but would be a nice feature.

**Comment by genievot** [comment]
having such a feature will be a great idea.

**Comment by trantansang** [comment]
I need to add custom domain to application. Please help

**Comment by pchico83** [comment]
This is now supported in our Developer Pro Plan.
Contact support@okteto.com to set it up.
