### ISSUE TITLE
how to remove used disk storage ? 

### ISSUE THREAD

**Issue by izzatzr** [okteto/cloud-feedback#19]
application get removed by clicking "Destroy" button in web panel , but disk storage used by the app not removed . is there any solution to solve this ?

**Comment by rberrelleza** [comment]
For now, you need to delete the underlying PVC using `kubectl`. We'll make this visible  from the UI in the near future.

**Comment by izzatzr** [comment]
> For now, you need to delete the underlying PVC using `kubectl`. We'll make this visible from the UI in the near future.
> 
> We'll use this issue to track it.

Thank you, solved

**Comment by pchico83** [comment]
@izzatzr thanks for reporting this one. I created #20 to track the issue
