### ISSUE TITLE
Elasticsearch cannot run

### ISSUE THREAD

**Issue by shyim** [okteto/cloud-feedback#25]
I cannot change vm.max_map_count so Elasticsearch cannot run in Okteto Cloud

**Comment by pchico83** [comment]
Validate with:
https://rancher.com/blog/2018/2018-11-22-deploying-elasticsearch/

**Comment by pchico83** [comment]
We have increased the node virtual memory limits in Okteto Cloud, it will go live on our next release

**Comment by shyim** [comment]
When its the next release?

**Comment by pchico83** [comment]
We are in the middle of a big UI change, it will go live middle next week

**Comment by pchico83** [comment]
@shyim we had to release a hotfix and I cherry-picked this commit. It is now available in Okteto Cloud
