### ISSUE TITLE
Exposed port message is hardcoded to 8080

### ISSUE THREAD

**Issue by kkapelon** [okteto/cloud-feedback#27]
I just deployed an image to Okteto cloud from the GUI
I selected image sonatype/nexus3 and port 8081

However after deployment has finished I click on the link in okteto cloud and get a message 

"Your environment is ready!
Go to your Okteto terminal and start your service on port 8080."

After some time the deployment works, but I was confused for a second. The UI should mention the port I used instead of always mentioning 8080

**Comment by rberrelleza** [comment]
Thanks for filing the issue, this is now fixed!
