### ISSUE TITLE
Configuring KMS for securing secrets

### ISSUE THREAD

**Issue by Jahn08** [okteto/cloud-feedback#28]
In Kubernetes secrets are stored as text encoded in base64, which is not encryption at all and therefore provides no security. However, additionally one can apply EncryptionConfiguration files to a server through the _kube-apiserver_ utility and turn on not only encryption at REST, but also set up storing encryption keys externally with Key Manager Service (KMS).

It would be great to implement the options for connecting to a KMS provider in the Okteto's settings menu too, because right now as a user I seem not to be able to set up KMS, since I don't have a direct access to _kube-apiserver_.

**Comment by rberrelleza** [comment]
@Jahn08  would offering encryption at REST be enough for you, or you want to be able to bring your own encryption provider to your namespaces?

**Comment by Jahn08** [comment]
@rberrelleza that's great news! Thank you!
However, in the kubernetes [documentation](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers) they acknowledge that 
> Storing the raw encryption key in the EncryptionConfig only moderately improves your security posture, compared to no encryption. Please use kms provider for additional security.

So, this appears to be the best option in terms of securing data and it's likely to be useful for other users as well.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
