### ISSUE TITLE
Vault integration

### ISSUE THREAD

**Issue by RealHarshThakur** [okteto/cloud-feedback#31]
Installing Hashicorp's Vault requires Cluster level permissions. Is there way to provide Vault as a service?

**Comment by pchico83** [comment]
@harshthakur9030 
We have added support for Okteto Secrets from the Okteto Cloud UI.
Does it fit your requirements?
https://okteto.com/docs/cloud/secrets.html

**Comment by harshthakur9030** [comment]
That's a nice feature but if you could provide Vault in some way, that would be great. Vault lets you have dynamic credentials for databases and has a plethora of options for authentication for an identity.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
