### ISSUE TITLE
Restart pod from website

### ISSUE THREAD

**Issue by TrungNguyen1909** [okteto/cloud-feedback#32]
Basically, a restart button on the website, which somewhat equivalent to `kubectl rollout restart deployment/deployment-name` would be nice as sometimes without my computer, I couldn't really manage anything. Before a proper fix is delivered in the code, some issues like deadlocks could be temporary fixed just by restarting a pod.

**Comment by rberrelleza** [comment]
you can now restart deployments and stateful sets from the UI.
