### ISSUE TITLE
Automatic Deploy from docker hub

### ISSUE THREAD

**Issue by TrungNguyen1909** [okteto/cloud-feedback#33]
I'd love an option that automatically create a webhook on Docker Hub that fires back anytime an image is pushed and then pull the new image and then restart the container.
The automatic deploy tag should be an customizable option as deploying an unstable branch on production is never good.
OTOH, user chooses a tag and then when an image is pushed to that tag, a new image is pulled and the pod is restarted.

**Comment by tullo** [comment]
Are you aware of the okteto github actions? @TrungNguyen1909 

You can narrow down the trigger for automatic build and deployment to a specific branch/events at the top of the job specification
An example:
```
on:
  push:
    branches:
      - master
```
https://github.com/rberrelleza/actions-test/blob/master/.github/workflows/main.yaml
https://github.com/okteto/actions
