### ISSUE TITLE
Show Docker images from the Okteto registry in the Okteto cloud UI

### ISSUE THREAD

**Issue by kkapelon** [okteto/cloud-feedback#35]
I just tried the Okteto registry and it works great both from command lines and other registry viewers. Congrats!

It would be nice however to also have a basic image viewer in the okteto cloud UI. At the very least I would like to see

- name/tag of docker image
- when it was pushed
- size of image
- total size of all images in my account

Also it is not clear from the docs. What happens if I delete a namespace? Are all images associated with it also removed?

**Comment by rberrelleza** [comment]
@kkapelon  If you delete your namespace the images in it will be deleted as well (not immediately, but in the next cleanup job). I'll update the docs to make this super clear.

**Comment by jvgrootveld** [comment]
I was wondering what the limits are for the free tier.
I guess it uses the storage in the “namespace”? So what happens when it reaches the max?

I think a simple viewer with delete functionality would suffice.

**Comment by rberrelleza** [comment]
Update:  we currently use the docker registry, and the APIs for this sort of thing is fairly limited. We're evaluating the migration to another registry, like harbor or portus to enable this. We'll have another update in march.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
