### ISSUE TITLE
Updating OpenFaaS password not working 

### ISSUE THREAD

**Issue by Janaka-Steph** [okteto/cloud-feedback#39]
Hello,

I tried to update the OpenFaaS password but this is not working.

Step to reproduce:
On Okteto Cloud, click "Upgrade" on OpenFaaS app, change the password to 'my_new_password', click "upgrade" to save.

Expectation:
`echo 'my_new_password' | faas-cli login -u admin --password-stdin` will log me successfully.

**Comment by rberrelleza** [comment]
This is now fixed, a secret is created/updated on install and upgrade.
