### ISSUE TITLE
Inter namespaces traffic

### ISSUE THREAD

**Issue by mpolatcan** [okteto/cloud-feedback#40]
Hello Okteto team :)  Users have at least 3 namespace on Okteto and that I want to use more efficient that namespaces with communicate pods in different namespaces of my account :)

**Comment by rberrelleza** [comment]
Thanks for the feedback @mpolatcan . The idea with multiple namespaces in okteto is that they are isolated environments (e.g. for dev, staging and prod). 

What's your use case for cross-namespaces communication VS putting everything on the same namespace?

**Comment by mpolatcan** [comment]
There is available 8 gb ram for each namespace on Okteto. But I want to use 16gb ram for my Kafka or Spark cluster on Kubernetes for processing test data. Maybe, total ram which it is 24 GB can be split equally when user opens new namespaces. For example, when only available one namespace that namespace's ram is 24, after open one namespace again split up to 12gb, 12gb respectively. After open last namespace, each namespace has 8 gb ram :)

**Comment by filipecaixeta** [comment]
I would like to do namespace communication because I keep my databases in a different namespace than my application

**Comment by pchico83** [comment]
@filipecaixeta thanks for the feedback. We have received the same feedback several times. We are testing this functionality already in our integration environments, it will go live before the end of the week

**Comment by pchico83** [comment]
@filipecaixeta @mpolatcan this feature is not available in Okteto Cloud

**Comment by mpolatcan** [comment]
Due to you have changed quotas and namespaces count. Also reduced available memory amount for each user. I don't use Okteto anymore because my personal computer's memory greater than okteto platform. Instead of Okteto i am using Tilt now that is more flexible 👎
