### ISSUE TITLE
Can't deploy an application if the helm repo is in a subpath

### ISSUE THREAD

**Issue by rberrelleza** [okteto/cloud-feedback#41]
An application fails to be deployed if the helm repo is in a subpath, and the charts in `index.yaml` use relative URLs. This is the case for https://argoproj.github.io/argo-helm.

**Comment by hbstarjason** [comment]
Here's what I did :

1、Add repository

Add https://argoproj.github.io/argo-helm in the url https://cloud.okteto.com/#/settings/repositories

Prompt success

2、Deploy

Clicking on any of the charts prompts the following red prompt:


Failed get chart configuration from repository

**Comment by pchico83** [comment]
@hbstarjason thanks for reporting it. The fix is already implemented, it will go live tomorrow
