### ISSUE TITLE
[Suggestion] Add a option to have reachable URLs for MongoDB instances in Okteto Cloud

### ISSUE THREAD

**Issue by ajhalili2006** [okteto/cloud-feedback#45]
**Is your feature request related to a problem? Please describe.**
I hate the mess of installing the `kubectl` and the CLI, then do `kubectl exec -i <pod-name-here-someRandomPodIDHere> -- bash` then connect to the DB with `mongo`.

**Describe the solution you'd like**
Add an option to have reachable URLs for MongoDB instances in Okteto Cloud in the form of `pod-name-of-mongodb-instance-namespace.cloud.okteto.net`, like any others

**Describe alternatives you've considered**
Let me think about it soon.

**Additional context**
n/a

**Comment by rberrelleza** [comment]
Thanks for the feedback @AndreiJirohHaliliDev2006 ! 

What are you trying to accomplish by connecting to a MongoDB instance directly from your local machine?

**Comment by AndreiJirohHaliliDev2006** [comment]
> Thanks for the feedback @AndreiJirohHaliliDev2006 !
> 
> What are you trying to accomplish by connecting to the MongoDB instance directly from your local machine?

1. Install `kubectl` and the Okteto CLI.
2. Sign in to `cloud.okteto.com` with `okteto login -t [CENSORED]` (because I am using Okteto in a Gitpod workspace.)
3. Check if everything is right with `kubectl get pods`.
4. Connect to the pod's Bash interactive console with `kubectl exec -i <pod-name-here-someRandomPodIDHere> -- bash`.
5. Type `mongo` for accessing MongoDB's interactive shell.

But I don't know on connecting to MongoDB instance in Okteto Cloud without messing things up like what I did above.

**Comment by pchico83** [comment]
@AndreiJirohHaliliDev2006 are you running gitpod from www.gitpod.io? Or do you run it inside Okteto Cloud?

**Comment by AndreiJirohHaliliDev2006** [comment]
> @AndreiJirohHaliliDev2006 are you running gitpod from [www.gitpod.io](http://www.gitpod.io)? Or do you run it inside Okteto Cloud?

Yes, I am using the Okteto CLI in Gitpod. @pchico83

**Comment by pchico83** [comment]
@AndreiJirohHaliliDev2006 we are thinking about adding a cloud IDE (theia or coder or something similar) to the Okteto Application Catalog. This way, you would have direct access to the services running in your okteto namespace, and you would have direct access to `kubectl` and `okteto` cli commands from your IDE too.
Would that better fit your use case?
Exposing public TCP ports via kubernetes ingress is hard.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
