### ISSUE TITLE
Provide Kustomize as a default command in git installation job.

### ISSUE THREAD

**Issue by abhioncbr** [okteto/cloud-feedback#49]
Reference, https://okteto.com/docs/cloud/deploy-pipeline

Okteto installation job consist following command, 

- helm
- kubectl
- okteto
- skaffold
- bash
- make
- git
- openssh
- curl

I would be great to have Kustomize too. Thanks.

**Comment by rberrelleza** [comment]
Kustomize 3.8 is now included in the list  of default tools.
