### ISSUE TITLE
Can't push image to registry

### ISSUE THREAD

**Issue by ianwalter** [okteto/cloud-feedback#50]
If I run:

```
okteto build -t okteto.dev/$name .
```

I get:

```
 i  Running your build in Okteto Enterprise...
[+] Building 0.0s (0/0)
 x  build failed: failed to solve: rpc error: code = Unauthenticated desc = invalid okteto token, run `okteto login` and try again
```

 I have run `okteto login okteto.$subdomain` beforehand.

Also, when I try to login with Docker:

```
docker login registry.okteto.$subdomain
```

I get:

```
Error response from daemon: Get https://registry.okteto.$subdomain/v2/: x509: certificate is valid for *.$subdomain, not registry.okteto.$subdomain
```

Do I need to add an additional DNS entry specifically for the registry?

**Comment by rberrelleza** [comment]
When login with docker, the registry address to use is: `docker login registry.$subdomain`, without the okteto part.

**Comment by rberrelleza** [comment]
Can you try running okteto build -t registry.$subdomain/$namespace/$image:$tag instead?

This is to troubleshoot if the issue is with the client, or in the registry auth layer.

(If you prefer, we can also troubleshoot this in our community channel in the kubernetes slack: https://slack.okteto.com)
