### ISSUE TITLE
K8s1.19 hierarchical namespace feature.

### ISSUE THREAD

**Issue by abhioncbr** [okteto/cloud-feedback#51]
With the release of the hierarchical namespace feature in the K8s 1.19 release, I think it's much of usage in the environment like Okteto since we are assigned to our individual namespace.

**Comment by rberrelleza** [comment]
@abhioncbr very interesting. would you mind elaborating in the use cases you see for this? (e.g.  would you like to be able to create hierarchical namespaces, or are you thinking that all okteto-managed namespaces should be hierarchical?)

**Comment by abhioncbr** [comment]
I am having a developer account and hence have only one namespace; I see a value in the hierarchical namespace, but not sure it is valuable for everyone. I must say It should be a flag based, by default, maybe false. 

Also, I did notice Okteto is currently 1.16, not sure journey down the 1.19 line will be how long.

**Comment by rberrelleza** [comment]
That's a cool use case. We don't have an ETA on 1.19, but we'll keep the ticket updated.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
