### ISSUE TITLE
Feature request: Ability to download whole container log

### ISSUE THREAD

**Issue by shinebayar-g** [okteto/cloud-feedback#53]
I don't know if it's limited by kubernetes itself or not. But after a while container logs are truncated and it's not visible anymore. Of course it would be insane to display whole container log on a web. Alternatively it would be great to download log files from the website. Or even better you could implement log aggregation feature like cloudwatch and offer it?

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
