### ISSUE TITLE
Make the client-ip available on my pods

### ISSUE THREAD

**Issue by rberrelleza** [okteto/cloud-feedback#55]
When my app gets an http request, the X-REAL-IP and X-FORWARDED-FOR headers only contain the pod and load balancer's  IP. Having the customer IP would help me do things like geolocalization, save preferences, identify anonymous users, etc.

**Comment by iMro0t** [comment]
+1

In my case i want to allow user specific content to their whitelisted IP only. But i can't find the real client IP anywhere. 
X-Forwarded-For , X-Real-IP both headers giving internal pod's IP address. I tried custom ingress-nginx but still no luck with that.

Is there any workaround as of now ?

**Comment by rberrelleza** [comment]
@iMro0t we're investigating options, we'll update this ticket once we have a work around.

**Comment by patrickkusebauch** [comment]
This is a really useful feature for whitelisting.

Okteto is prime for being used as a very early place to present the app to the client and most clients would want their application to not be accessible to anybody else.

**Comment by pchico83** [comment]
Hi @patrickkusebauch 
I am wondering if whitelisting at the ingress level would work for you.
You can set this annotation in your ingress manifest:
```
nginx.ingress.kubernetes.io/whitelist-source-range
```
also, we also support private endpoints, which are only accessible by your github id user:
https://okteto.com/docs/cloud/private-endpoints
would that work?

**Comment by patrickkusebauch** [comment]
Hello, @pchico83 
I do not have a separate ingress config yet, I am using annotation on the service, will try it out.

I had a look at private endpoints, the issue I see is that it requires the end-user of the application to be a little bit `tech-savvy` and configure access on their side. With an IP whitelist it is the developer who has to do the configuration.

**Comment by patrickkusebauch** [comment]
@pchico83 I have tried
```
kubectl describe ingress
Name:             web
Namespace:        patrickkusebauch
Address:          34.123.88.79,35.238.195.0
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" is forbidden: User "system:serviceaccount:okteto:615de93b-b154-4ee4-a217-13b5ce5b02ad" cannot get resource "endpoints" in API group "" in the namespace "kube-system">)
TLS:
  SNI routes web-patrickkusebauch.cloud.okteto.net
Rules:
  Host                                   Path  Backends
  ----                                   ----  --------
  web-patrickkusebauch.cloud.okteto.net  
                                         /   web:80 (10.4.3.84:80)
Annotations:                             dev.okteto.com/generate-host: true
                                         kubernetes.io/ingress.class: nginx
                                         nginx.ingress.kubernetes.io/default-backend: web
                                         nginx.ingress.kubernetes.io/limit-connections: 20
                                         nginx.ingress.kubernetes.io/limit-rpm: 200
                                         nginx.ingress.kubernetes.io/limit-rps: 20
                                         nginx.ingress.kubernetes.io/whitelist-source-range: x.x.x.x, y.y.y.y
```

where `x.x.x.x` and `y.y.y.y` are values provided by googling `What is my IP` while inside and outside VPN. In both cases, the result is `HTTP 403` from the ingress. If I remove the whitelist, the Ingress works fine as to the routing to the app.

**Comment by pchico83** [comment]
@patrickkusebauch we need to make a change in our ingress configuration to support those annotations. I will let you know once it is ready

**Comment by pchico83** [comment]
@patrickkusebauch the ingress configuration changes are now available in Okteto Cloud.
Could you try using those annotations again?

**Comment by patrickkusebauch** [comment]
@pchico83 Great tried it and it works flawlessly. Thank you for your help. Now we only need the client IP inside the pod.... :smile:

**Comment by pchico83** [comment]
Having the client-ip at the pod level is not supported in Okteto Cloud (it is supported in Okteto Enterprise).
This is because all services in Okteto Cloud are `ClusterIP` type (`NodePort` and `LoadBalancer` service types are not supported), and Kubernetes does not expose the client-ip when going through a `ClusterIP` service.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
