### ISSUE TITLE
add support to externalname in service

### ISSUE THREAD

**Issue by chaowenGUO** [okteto/cloud-feedback#57]
apiVersion: v1
kind: Service
metadata:
    name: page
spec:
    type: ExternalName
    externalName: chaowenguoorg.github.io
    ports:
    - port: 443

not working in okteto cloud, if I use kubectl get svc and just see
page        ClusterIP   10.132.26.203   <none>        443/TCP
It seems that okteto not support type: ExternalName

**Comment by rberrelleza** [comment]
We support this through our [custom domains feature](https://okteto.com/docs/cloud/custom-domains/index.html). Feel free to reach us out at support@okteto.com and we can enable this for you.
