### ISSUE TITLE
For deploy button, allow secure access to private github repository login using ssh

### ISSUE THREAD

**Issue by plouismarie** [okteto/cloud-feedback#59]
So far the only authentication mode I was able to use successfully was https url with password nested  :

https://<login:pass>@github.com/<github_username>/<repo>.git

That works but it exposes the password in clear, and that is not really desired.

Github is compliant with ssh login, hopefully okteto login would be also, via that feature request.

---------------

As discussed with Ramiro, there is a current workaround : have a dummy public github repo ( so no auth needed ) used for the deploy button, and that public repo, would clone its content from a private repo where the real content is.

For instance with an “okteto-stack.yaml” file than then does the clone using the token from your secret, and deploy the app

It is an indirection but it seems to work in the meantime something better/simpler got figured out

**Comment by rberrelleza** [comment]
@plouismarie you can know use private github repositories with okteto cloud. This works both for the "deploy" button as well as in a pipeline. Give it a try, and let us know what you think! (I'll close this for now, but feel free to open it if you require something more).

**Comment by plouismarie** [comment]
awesome !!
just tested it, my test is successful.
Thx a bunch :)
