### ISSUE TITLE
allow access to private github repo via ssh key for deploy button

### ISSUE THREAD

**Issue by plouismarie** [okteto/cloud-feedback#60]
So far the only authentication mode I was able to use successfully was https url with password nested  :

https://<login:pass>@github.com/<github_username>/<_repo>.git

That works but it exposes the password in clear, and that is not really desired.

Github is compliant with ssh login, hopefully okteto login would be also, via that feature request.

---------------

As discussed with Ramiro, there is a current workaround : have a dummy public github repo ( so no auth needed ) used for the deploy button, and that public repo, would clone its content from a private repo where the real content is.

For instance with an “okteto-stack.yaml” file than then does the clone using the token from your secret, and deploy the app

It is an indirection but it seems to work in the meantime something better/simpler got figured out

**Comment by rberrelleza** [comment]
This is now available, go to the deploy dialog, and click on the link to enable access to private repositories!
