### ISSUE TITLE
Put namespace into the Destroy Resource modal

### ISSUE THREAD

**Issue by itsmeniko** [okteto/cloud-feedback#61]
Hi,

Just a thought, it might be useful for preventing mistakes, if the namespace was put on the modal for destroying a resource, e.g.: 

![image](https://user-images.githubusercontent.com/52934076/106942473-72862200-66e1-11eb-9a32-17609e46e57f.png)

for users that operate in many different namespaces, this could help them avoid deleting the wrong resource.

Thanks

**Comment by rberrelleza** [comment]
This is a great idea, thanks for the suggestion!

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
