### ISSUE TITLE
Manage Okteto secrets from cli

### ISSUE THREAD

**Issue by rimusz** [okteto/cloud-feedback#63]
creating Okteto secrets from the cli: `okteto create secret secret_name`
pulling (get value) Okteto secrets from the cli: `okteto secret secret_name`

**Comment by rimusz** [comment]
cc @rberrelleza

**Comment by rimusz** [comment]
ping :)

**Comment by pchico83** [comment]
@rimusz what was the use case for this?

**Comment by rimusz** [comment]
As I have mentioned in the slack chat, it would be helpful to create secrets from local run or CI.
Also for pulling it locally as for some of my deployments I want to use only `okteto build` but then secrets are missing.

**Comment by pchico83** [comment]
@rimusz it is not implemented yet, but we will autoinject secrets in the environment of every okteto command.
We will implement support for creating/deleting secrets, but not to get their values directly

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
