### ISSUE TITLE
Support for deploying a docker-compose file

### ISSUE THREAD

**Issue by pchico83** [okteto/cloud-feedback#64]
[Okteto Stacks](https://okteto.com/docs/reference/stacks) should be able to deploy a docker-compose file.
The [git deployment automatic pipeline](https://okteto.com/docs/cloud/okteto-pipeline#automatic-deployment) should be able to deploy docker-compose files

**Comment by rberrelleza** [comment]
We now support docker-compose in Okteto Cloud https://okteto.com/blog/how-to-develop-docker-compose-applications-remotely-in-okteto-cloud/ 🥳
