### ISSUE TITLE
Support folders to store pipeline files

### ISSUE THREAD

**Issue by rimusz** [okteto/cloud-feedback#65]
Support folders to store pipeline files: `.okteto/okteto-pipeline.yml`

**Comment by pchico83** [comment]
@rimusz would this be just an alternative (fixed) location for the `okteto-pipeline.yml` file? or would you want it to be configurable?

**Comment by rimusz** [comment]
I think it makes sense to make location configurable

**Comment by pchico83** [comment]
@rimusz where would you configure it? at pipeline deployment time? or using a default okteto metadata file?

**Comment by rimusz** [comment]
`-f` could be used to to set the location/file.
Also make as default:
- current one in root `okteto-pipeline.yml`
- `.okteto/pipeline.yml`

**Comment by pchico83** [comment]
@ifbyol This would be a nice addition :-)

**Comment by rimusz** [comment]
was this implemented?

**Comment by ifbyol** [comment]
@rimusz Hi! the feature was implemented but it wasn't on time to be on today's CLI release. It will be available on the next release. I'll let you know once it is released
