### ISSUE TITLE
Helm autodetection does not seem to work

### ISSUE THREAD

**Issue by kostis-codefresh** [okteto/cloud-feedback#69]
I am trying to deploy from git my Helm project at https://github.com/codefresh-contrib/helm-sample-app

The Helm chart is in a folder called **charts** and according to the docs this should be identified by Okteto https://okteto.com/docs/cloud/okteto-pipeline 

>if your repository has a chart, charts, helm/chart, or helm/charts directory with a Chart.yaml file in it, Okteto will detect the chart and run helm upgrade --install on it.

But the deployment fails: see attached screenshot

![fail-helm](https://user-images.githubusercontent.com/39800303/120013450-694ef700-bfe9-11eb-84a6-1a797bff2e7c.png)

**Comment by pchico83** [comment]
@kostis-codefresh looks like the chart is in the path `charts/helm-example`, not `charts`.
I will create an issue to support this scenario too

**Comment by kostis-codefresh** [comment]
Ah my bad. I assumed the functionality was recursive

Yes I think that making it more lenient would be great for usability

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
