### ISSUE TITLE
Rewrite the PVC configuration instead of failing

### ISSUE THREAD

**Issue by rberrelleza** [okteto/cloud-feedback#71]
Instead of failing with a cryptic message, okteto cloud should remove / rewrite parts of the PVC that are not valid. E.g. the  storageClass and accessModes.

**Comment by pchico83** [comment]
What is the error returned to the user? It could be confusing to do those rewrites without user intervention.
Maybe a clear error message is better

**Comment by rberrelleza** [comment]
When the pod is waiting, it gets this error:

```

**Comment by pchico83** [comment]
@ifbyol could we have a list of supported storage classes and fail the PVC creation if the storage class is not supported?
