### ISSUE TITLE
dashboard today (2021, June 17) and yesterday(June 16) does not update from  "processing" to "deployed"

### ISSUE THREAD

**Issue by jstnjstn** [okteto/cloud-feedback#73]
perhaps you guys can check this on firefox browser. the okteto dashboard is not updating to deployed for various deployements I have been trying, today and yesterday. Need to hit F5 to reload to show all is well and deployed.

**Comment by pchico83** [comment]
@jstnjstn is it still happening? we released a fix for this yesterday

**Comment by jstnjstn** [comment]
It seems going from processing to deployed works now.  
Today I found destroying does not update the UI. Since the same underlying issue, please check that as well. Thank you.

**Comment by pchico83** [comment]
@jstnjstn is destroying still an issue? 
@maroshii ^^

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
