### ISSUE TITLE
MEVN sample

### ISSUE THREAD

**Issue by jstnjstn** [okteto/cloud-feedback#75]
Please add a MEVN example to the list on https://github.com/okteto/samples
I couldn't see "Vue" or "MEVN" in the text. 
Perhaps you could list the recipe app 
https://github.com/rberrelleza/cloud-native-recipes-compose
as referred also in the talk
https://dok.community/schedule/recMMUA9qUrls3tXk/
if it is suitable and ready with a note to say decrement vote in the app does not work on purpose to illustrate a point made in the talk about debuggability with okteto.
Thanks.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
