### ISSUE TITLE
secret : change value button

### ISSUE THREAD

**Issue by jstnjstn** [okteto/cloud-feedback#76]
Perhaps you can add a button to assign a new value to an existing secret from the dashboard. Would save having to delete and add the same key name for the secret.

**Comment by jstnjstn** [comment]
...or save typing in the key name again when "over" add'ing.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
