### ISSUE TITLE
Add cue binary to the pipeline?

### ISSUE THREAD

**Issue by jakedt** [okteto/cloud-feedback#78]
We use [cue](https://cuelang.org/) to render all of our templates as a substitute for helm. It would be nice to have the cue binary in the pipeline runner.

**Comment by rberrelleza** [comment]
that's a great idea @jakedt! I'll update this ticket once it's available.

**Comment by rberrelleza** [comment]
@jakedt cue is now available on the pipeline in cloud.okteto.com! 

Any chance you have a public repo we can use to try it out?
