### ISSUE TITLE
Cannot pull OCI images

### ISSUE THREAD

**Issue by CtrlZvi** [okteto/cloud-feedback#79]
It appears that Okteto is using an old version of docker as its container runtime, which prevents the pulling of OCI images. Attempting to do so results in `Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not ''`

This seems to be the same error as docker/hub-feedback#1871, which was fixed in Docker 19.0.3.5.

**Comment by rberrelleza** [comment]
thanks for reporting this @CtrlZvi , we are investigating our options, and will update the issue soon. 

To help us with our validation, what image where you trying to deploy?

**Comment by CtrlZvi** [comment]
Just build a new version of the image and tried to deploy again to repro:
```
2021-08-12 02:26:44.00 UTCreview-repro-luhyfc-mediawiki-database-76fb86b7fb-gp2jl[event]Back-off pulling image "registry.gitlab.com/wikipartments/mediawiki/database:9581cbba"
2021-08-12 02:26:44.00 UTCreview-repro-luhyfc-mediawiki-database-76fb86b7fb-gp2jl[event]Error: ImagePullBackOff
```
This is from the `review-repro-luhyfc` chart in the `ctrlzvi` namespace.

If you need an example from not a private registry let me know and I'll create a public registry repro case.

**Comment by pchico83** [comment]
@CtrlZvi we have upgraded to Kubernetes 1.20 which comes with a new container runtime.
Could you validate if this is still an issue?

**Comment by CtrlZvi** [comment]
The upgrade has resolved this and this is no longer an issue.
