### ISSUE TITLE
Add helmfile as built-in tool of the Okteto Pipeline

### ISSUE THREAD

**Issue by martingutsche** [okteto/cloud-feedback#80]
I use [helmfile](https://github.com/roboll/helmfile) to manage the deployment of multiple helm charts. It would be nice to have the helmfile binary in the pipeline runner image. Is that something you would be willing to add?

If not, what would be the recommended way to get the binary in the container? Installing it as part of the `deploy:` commands seems painfully slow and inefficient.

**Comment by pchico83** [comment]
@martingutsche I think it is a nice addition in our default pipeline image. We should have it ready during this week

**Comment by ifbyol** [comment]
Hi @martingutsche ! We have added `helmfile` to the pipeline runner image. It should be already available in Cloud
