### ISSUE TITLE
Add node binary to the pipeline?

### ISSUE THREAD

**Issue by maykefreitas** [okteto/cloud-feedback#81]
Hi. What about add nodejs binary in the pipeline? I use to write some pre-processing scripts in node.

**Comment by pchico83** [comment]
@maykefreitas you should be able to install it as part of your pipeline

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
