### ISSUE TITLE
SOPS over Flux problem

### ISSUE THREAD

**Issue by jhonatanTeixeira** [okteto/cloud-feedback#83]
i´ve installed flux on okteto, so far it worked nicely, however now i want to use SOPS for secrets encryption, and i get this error when i run the following command. 

```bash
$ flux create kustomization my-secrets --source=my-secrets --path releases/secrets --prune=true --interval=10m --decryption-provider=sops --decryption-secret=sops-gpg 
```

```
no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta2"
```

It seens that i cant run the flux install, i end up with permission denied, so how can i get SOPS to work on okteto?

Pablo replied me this:

Looks like we need to install some Flux CRDs in the cluster

How can we fix this issue?

Thanks guys

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
