### ISSUE TITLE
Wrong error - Service is running but not listening

### ISSUE THREAD

**Issue by mladedav** [okteto/cloud-feedback#85]
I am getting a 502 error from Okteto, which I assume is pretty standard in the beginning. However the message is wrong as I have checked that my pod is running and it is listening at the given port. The issue is that there is an okteto-unrelated bug which makes the HTTP handler (not the whole application) crash and the application does not send back any message and closes the TCP connection. Other endpoints work.

Okteto seems to assume that the application is not listening (prompting me to hunt for kubernetes service and deployment-related configuration errors) while that is not the case. The backend should know at that point that the TCP connection was estabilished so there is another issue.

I am using the auto-ingress feature which uses custom pages for these errors so I think the text in there should be changed appropriately if there is no way to make nginx discern which error actually happened.

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
