### ISSUE TITLE
Support for Wordpress !

### ISSUE THREAD

**Issue by BlackBox-cmd** [okteto/cloud-feedback#88]
Is It possbile that can i install Wp on Okteto ...

**Comment by rberrelleza** [comment]
You can install it as part of your development environment by defining a pipeline: https://www.okteto.com/docs/cloud/okteto-pipeline/

What's your use case for wordpress?

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
