### ISSUE TITLE
Error when deploying helm release that contains a job

### ISSUE THREAD

**Issue by davemaier** [okteto/cloud-feedback#89]
Hi, I have a helm chart that contains a few jobs (see the example for a hob template below). And every time I try to deploy this chart I get the following error message 

```! Error: UPGRADE FAILED: failed to create resource: Post "https://localhost:40459/apis/batch/v1/namespaces/pr-36-cfs-dev-user/jobs?fieldManager=helm": stream error: stream ID 391; INTERNAL_ERROR; received from peer error executing command 'Run helm upgrade': exit status 1```

If I deploy the chart without the jobs, everything works fine. The strange thing is that this is that this has not been making any problems till now and I didn't change anything.

Example of the job:
```apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-assist
spec:
  template:
    spec:
      containers:
        - name: migrate-assist
          image: registry.cloud.okteto.net/pr-36-cfs-dev-user/ava-api-assist@sha256:910fc438994c2866f52b1bb0c205f905e467ad4973bb0cfd1baae3cc5481d7ed
          command: ["yarn", "migrate", "deploy"]
          env:
            - name: "DATABASE_URL"
              value: postgresql://okteto:okteto@postgresql:5432/assist
      restartPolicy: "OnFailure"```

**Comment by pchico83** [comment]
@davemaier which command are you using to deploy the chart? are you using `helm` directly or via `okteto deploy`?

**Comment by davemaier** [comment]
I'm deploy using the github action ´okteto/pipeline@latest´ and a okteto.yml file that has a deploy section containing the ´helm upgrade --install´ command. All my services and deployments work fine, but the jobs fail to deploy. Deploying the jobs via ´kubectl´ works fine.

**Comment by pchico83** [comment]
@davemaier could we have a repro git repository? I have tried to deploy jobs with no issue so far

**Comment by davemaier** [comment]
Thanks for trying to reproduce the error @pchico83 ! Here is a repo that produces the same error.
https://github.com/davemaier/job-deploy-test

**Comment by pchico83** [comment]
@davemaier we have identified the issue and we are working on a fix now.
In the meantime, if you add labels to your container spec, you should workaround the issue:
https://github.com/davemaier/job-deploy-test/blob/main/chart/templates/migrate-assist.yaml#L7

**Comment by davemaier** [comment]
Great! Thanks a lot!

**Comment by davemaier** [comment]
Hmm, somehow I can't make it work with the workaround, could you post an example of a working job definition? @pchico83

**Comment by davemaier** [comment]
Yay, I could finally figure it out. I missed that the template spec also has a metadata.labels property. Everything works fine now.

**Comment by pchico83** [comment]
> Yay, I could finally figure it out. I missed that the template spec also has a metadata.labels property. Everything works fine now.

awesome! I was about to send you a quick sample. The fix on our side will go live next week
